### ISSUE TITLE
Perpendicular: angle instead of reverse

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#109]
Currently, we have a `reverse` prop on `Perpendicular` which rotates the component by 180 degrees. We should rename that prop to `angle` and accept a number so it'll be consistent with the `angle` prop on `Arrow`:

https://github.com/diegohaz/reakit/blob/4523918e64ee73ab5c9b87deb08b29eddd9af95c/src/components/Arrow/Arrow.js#L39-L45

`reverse` is used by two other components: `PopoverArrow` and `TooltipArrow`. These are the lines that should be updated:

https://github.com/diegohaz/reakit/blob/4523918e64ee73ab5c9b87deb08b29eddd9af95c/src/components/Perpendicular/Perpendicular.js#L24-L26

https://github.com/diegohaz/reakit/blob/4523918e64ee73ab5c9b87deb08b29eddd9af95c/src/components/Perpendicular/Perpendicular.js#L54-L66

https://github.com/diegohaz/reakit/blob/4523918e64ee73ab5c9b87deb08b29eddd9af95c/src/components/Popover/PopoverArrow.js#L18-L24

https://github.com/diegohaz/reakit/blob/4523918e64ee73ab5c9b87deb08b29eddd9af95c/src/components/Tooltip/TooltipArrow.js#L17-L23

A PR is very welcome. Since it's a breaking change, the PR should be sent to the `next` branch.

**Comment by Moeface** [comment]
I'm not sure if this is the right place for it, but the Popover.Arrow docs (https://reakit.io/components/popover/popoverarrow) already refer to the prop `angle`, but the `pos` string is actually the prop that modifies the behaviour of the component. Using `angle` does nothing.

**Comment by diegohaz** [comment]
Yes, @Moeface. That's one of the things this solution will fix. Currently, `Perpendicular` is overriding `angle`.
