### ISSUE TITLE
Refreshing inner pages shows 404

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#122]
We should copy `index.html` and rename it to `404.html` when building the website.

**Comment by Thomazella** [comment]
Can you give me some instructions to replicate it? I tried F5 on firefox and shift+F5 to override cache, but it doesn't show a 404 page.

**Comment by diegohaz** [comment]
@Thomazella You have to do that in one of the inner pages.

**Comment by diegohaz** [comment]
This looks like an overkill, but redirecting could be better than just using 404.html as index.html
https://github.com/rafrex/spa-github-pages

**Comment by Thomazella** [comment]
Ok. But to actually test a solution we'd need to deploy to gh right? I can probably do that with my fork...

**Comment by IniZio** [comment]
Maybe could use netilfy instead with _redirects config?
