### ISSUE TITLE
Question: Theme for Your Docs Website

### ISSUE THREAD

**Issue by twhite96** [diegohaz/reakit#143]
I am looking all over the place for this theme, which is the same one React uses. It is a Gatsby starter I think but I can't find it anywhere. Can you tell me which one you used?

Thanks a bunch.

**Comment by diegohaz** [comment]
Hey, @twhite96.

We're using [react-styleguidist](https://react-styleguidist.js.org/) to build the content. But there's no theme. It was built from scratch with ReaKit itself.

https://reactjs.org and https://vuejs.org were the main references.

You can find the code in the `website/src` folder.
