### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#2]
Any help with docs would be very welcome.

And, since I'm not a native English speaker, I could have made some mistakes. If you find an error, please do submit a PR with the correction.

Thank you, guys.

**Comment by lluia** [comment]
Hey @diegohaz, **Reas** looks cool! 

Really like:

- all components are stateless
- bound with styled components 💅🏻
- the concept of `as` to make `render` flexible everywhere 😍 
- [behaviours](https://diegohaz.github.io/reas/#styling) looks quite declarative ❤️ 
- [state](https://diegohaz.github.io/reas/#state) seems quite pluggable

I'm not contributing much to open-source right now but I would be happy to help writing with the docs or even writing some components.

I see you're using [styleguidist](https://react-styleguidist.js.org/) for the docs, could help with some styling on that too. 

I was inspecting the components' output with the *react devtools* and noticed there's a lot of stuff wrapping even a single button:

![reas_wrap](https://user-images.githubusercontent.com/5938217/35284928-f497d8b2-0053-11e8-9593-e7a21641765f.png)

is that because of _styled-components_ or the lib?

**Comment by diegohaz** [comment]
Hey, @lluia 

Thank you for the words. 

The component stack is due to how we make composition here. Currently, each component in `reas` is made of at least 8 components:

#### `button`
  The html element
  ```js
  <button />
  ```
#### [`Reas`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L12-L38)
  Wrapper around `button` so it has the benefits of a `reas` component
  ```js
  <Reas>
    <button />
  </Reas>
  ```
#### [`styled(Reas)`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L40-L48)
Wrapper around `Reas` so it is a styled component (and so is `button`)
```js
<styled(Reas)>
  <Reas>
    <button />
  </Reas>
</styled(Reas)>
```

#### [`Next`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L10)
This is what `Reas` uses to render `styled(Reas)` (and therefore `button`)
<details><summary>Stack</summary>
<pre>
&lt;Next>
  &lt;styled(Reas)>
    &lt;Reas>
      &lt;button />
    &lt;/Reas>
  &lt;/styled(Reas)>
&lt;/Next>
</pre>
</details>

#### [`Reas`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L12-L38)
Applies the benefits of `reas` to `Button` (the React component)
<details><summary>Stack</summary>
<pre>
&lt;Reas>
  &lt;Next>
    &lt;styled(Reas)>
      &lt;Reas>
        &lt;button />
      &lt;/Reas>
    &lt;/styled(Reas)>
  &lt;/Next>
&lt;/Reas>
</pre>
</details>

#### [`styled(Reas)`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L40-L48)
Makes `Button` a styled-component
<details><summary>Stack</summary>
<pre>
&lt;styled(Reas)>
  &lt;Reas>
    &lt;Next>
      &lt;styled(Reas)>
        &lt;Reas>
          &lt;button />
        &lt;/Reas>
      &lt;/styled(Reas)>
    &lt;/Next>
  &lt;/Reas>
&lt;/styled(Reas)>
</pre>
</details>

#### [`Button.as(button)`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L66-L67)
This is the component that correctly passes `as` to `styled(Reas)`
<details><summary>Stack</summary>
<pre>
&lt;Button.as(button)>
  &lt;styled(Reas)>
    &lt;Reas>
      &lt;Next>
        &lt;styled(Reas)>
          &lt;Reas>
            &lt;button />
          &lt;/Reas>
        &lt;/styled(Reas)>
      &lt;/Next>
    &lt;/Reas>
  &lt;/styled(Reas)>
&lt;/Button.as(button)>
</pre>
</details>

#### [`Button`](https://github.com/diegohaz/reas/blob/e76ac8cafdc856c2a4af48a9a840b8de1822008c/src/enhancers/as.js#L69-L70)
Finally
<details><summary>Stack</summary>
<pre>
&lt;Button>
  &lt;Button.as(button)>
    &lt;styled(Reas)>
      &lt;Reas>
        &lt;Next>
          &lt;styled(Reas)>
            &lt;Reas>
              &lt;button />
            &lt;/Reas>
          &lt;/styled(Reas)>
        &lt;/Next>
      &lt;/Reas>
    &lt;/styled(Reas)>
  &lt;/Button.as(button)>
&lt;/Button>
</pre>
</details>
<br /><br />


In addition, some components are already a composition of others. `Button`, for example, is a `InlineFlex.as(Box)`, which means that component stack will contain 16 more components, at least.

I know, that's kinda scary. It's currently in experimental phase and I'm not aware of all the performance impacts it has. But I think there're space to improve.

**Comment by lluia** [comment]
@diegohaz thanks for the explanation ❤️  

Have you thought to follow an approach similar to [recompact](https://github.com/neoziro/recompact) and squash all the _HOCs_ into a single one?

Not sure how it's implemented there but it looks they solved a very similar problem as the presented here 😉

**Comment by diegohaz** [comment]
With #36, component stack was reduced a little. Now we can see it within snaphots: 
- [stack array](https://github.com/diegohaz/reas/blob/89c7c2d7a1e885029350997579f7d3650bb92fd8/src/enhancers/__tests__/__snapshots__/as-test.js.snap#L4-L12);
- [full component stack](https://github.com/diegohaz/reas/blob/89c7c2d7a1e885029350997579f7d3650bb92fd8/src/enhancers/__tests__/__snapshots__/as-test.js.snap#L16-L65);
- [generated html](https://github.com/diegohaz/reas/blob/89c7c2d7a1e885029350997579f7d3650bb92fd8/src/enhancers/__tests__/__snapshots__/as-test.js.snap#L70-L73)

**Comment by diegohaz** [comment]
With #55, component stack will be hugely reduced, even compared to changes in #36:

Before:
![image](https://user-images.githubusercontent.com/3068563/38510320-09f72fd6-3bfb-11e8-8d10-45bb9723dc2f.png)

After:
![image](https://user-images.githubusercontent.com/3068563/38510312-029520a4-3bfb-11e8-814a-941342701216.png)

**Comment by diegohaz** [comment]
With #66 🎉
![image](https://user-images.githubusercontent.com/3068563/39080901-eaa581d4-450d-11e8-9044-a27ad91c444e.png)

**Comment by wordofchristian** [comment]
## Group components in the sidebar navigation

I think a great first step to improve the docs would be to group the components in the sidebar navigation. I found myself wanting to see all the components that have `State` components, or maybe this group would be called "Behavior Components" I'm extremely new to this project so I'm still figuring out what good groupings would be. Here's what I have so far:

- Behavior (Hidden, Step, Popover, ...)
- Presentational (Backdrop, Block, Box, Shadow, ...)
- Text (Heading, Label, Link, ...)
- Layout (Grid, Inline, Fit, InlineBlock, ...)

## Basic text explanations for all components

Another good thing to do would be to add basic text descriptions for each component (I have no idea what `<Fit />` does just by the example).  This is where the native english speakers can help. I'll try to help document as I learn the library better or I can help review any PRs that you make.

## Document component props, state components, and behaviors

Lastly, it would be good if every component had a description of the following

- Props that it can take (for example I don't know what `destroy` does on the `Hidden` component)
-  Any state component that it provides and document the shape of the object that gets passed to the child function ([downshift](https://github.com/paypal/downshift#render-prop-function) does a good job with this I think)
- Any behaviors the component provides (e.g `Hidden.Show`, `Hidden.Hide`)

**Comment by diegohaz** [comment]
Hi, @wordofchristian. Thank you so much for your feedback.

I agree with all your points. I still don't know how we should group components in docs, but I agree that it should be revisited.

I'm gonna send you an invite to be a collaborator on the project so you'll have more power on reviewing PRs and other things.

@Thomazella and I are actively working (on our free time) on new docs on the feature/docs branch. If you you'd like to join us, send me your email address and I'll invite you.

**Comment by Thomazella** [comment]
Nice. I agree too. Let's make these docs better! 🚀🚀⭐️🌈
