### ISSUE TITLE
Pronunciation of reas

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#40]
Yeah, I created this library and gave it a name that I don't even know how to pronounce.

I tend to call it `re-as`, but it's very hard to me to say `as` without sounding like `ass`. Because of that, it has a (no more) secret nickname: `rebunda` (`bunda` is `ass` in Portuguese), which leads to some nice verbs:

> Hey, don't you see I'm *rebunding* here?

> Let's *rebund* this shit!

I'm creating this issue to see how people read it and finally learn how to pronounce it correctly.

So, let's rebund it.

**Comment by bfillmer** [comment]
Around here we call it `ray-ass` so, there's that.

**Comment by klimcode** [comment]
[Google Translate](https://translate.google.com/) reads this word very close to "**reez**", and it sounds distant from "ass" which is read like "us".

I also have a proposal: you may add an article before "reas" and get the interesting effect:
"the reas" sounds like "**there us**"
"a reas" sounds like "**areas**" which is a completely safe name for a UI library.

**Comment by Thomazella** [comment]
My take on Reakit: ree - ACK - it
