### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#6]
With create-react-app, razzle etc.

**Comment by mgmgpyaesonewin** [comment]
Can I do this? What kinds of example, can I submit? Can I have any suggestion ? Thanks alot.

**Comment by diegohaz** [comment]
Sure, @mgmgpyaesonewin. It can be small projects using `reas` components. You can find some ideas for those projects searching by "react examples" on Google. These are good ones I found: https://dev.to/drminnaar/11-react-examples-2e6d

Here are some examples from other similar libraries:
- [Material-UI examples](https://github.com/mui-org/material-ui/tree/v1-beta/examples)
- [Semantic-UI examples](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/examples)
- [Belle examples](https://github.com/nikgraf/belle/tree/master/examples)
