### ISSUE TITLE
Automatic changelog

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#96]
We should use a tool to generate changelogs. It should support "beta" versions like `v0.10.0`.

**Comment by joao-alberto** [comment]
[Maybe this](https://conventionalcommits.org/)

**Comment by joao-alberto** [comment]
[Or this](https://github.com/github-changelog-generator/github-changelog-generator)

**Comment by diegohaz** [comment]
Will take a look at them. Thank you, @joao-alberto .

**Comment by joao-alberto** [comment]
@diegohaz I'll make tests with both of them to verify what fit best to our necessities
