### ISSUE TITLE
Hidden unmount

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#98]
Following #57 and #97, I think we should rename `destroy` prop to `unmount` on `Hidden`.

There are other components setting `destroy`. A global search and replace should do the job.

I'm opening a separate issue for that because it would be a breaking change. A PR should target the `next` branch.

EDIT: I'm also thinking about `styleProp`. Maybe it should be `hiddenStyle` and `visibleStyle` with some sane shortcuts:

```jsx
<Hidden
  hiddenStyle="display"
  hiddenStyle="visibility"
  hiddenStyle="opacity"
  hiddenStyle={{ width: 0 }}
  visibleStyle={{ width: "100%" }}
/>
```

**Comment by wordofchristian** [comment]
Agreed, I didn't rename it in #97 for that reason

**Comment by diegohaz** [comment]
More random thoughts: 

```jsx
// unmount instantaneously
<Hidden unmount />
// after visible gets falsy, wait 500ms to unmount
<Hidden unmount={500} />
// default duration and timing function
<Hidden fade slideUp slideDown slideLeft slideRight />
// setting ms with default timing function
<Hidden fade={500} slideUp={300} />
// anything
<Hidden fade="1.5s ease-in" />
// fading manually
<Hidden hiddenStyle="opacity" transition="opacity 1.5s ease-in" />
// fading manually 2
<Hidden hiddenStyle={{ opacity: 0 }} visibleStyle={{ opacity: 1 }} transition="opacity 1.5s ease-in" />
```

**Comment by Thomazella** [comment]
`fade` -> `hiddenTransition` maybe? aligns with `hiddenStyle` and `visibleStyle`, plus resembles css more. `unmount={500}` is hot, I like it! `slideUp` is a timing function that makes the component visually slide up? If so, we'd be hard coding this timing function into a custom prop we decided to call `slideUp`? If we need this type of behavior in other components maybe it should be encapsulated in its own thing.

**Comment by diegohaz** [comment]
@Thomazella I think this is how we could apply `slideUp` manually (didn't test it though):
```jsx
<Hidden
  hiddenStyle={{ transform: "translateY(100%)" }} 
  visibleStyle={{ transform: "translateY(0)" }}
  transition="transform 500ms ease-in-out"
/>
```

I think that's a good one to become a custom prop.

If people want to use it in other components, they could just use `<Foo as={Hidden} slideUp />`. It's hard to abstract animations too much because they usually depend on *at least* two states (0% and 100%, hidden and visible etc.). `Hidden` already comes with these states.

If we need to support other states in other components, we can think about an abstraction for it.

**Comment by wordofchristian** [comment]
Maybe the name of the component should be re-thought as well. Hidden implies that it will not be visible when what we want is something that switches between visible and invisible I'm wondering if maybe it would be more intuitive with a name like `<Visibility />` or `<Switch />`.

Here's what that would look like:

```javascript
<Visibility.Container>
  {visibility => (
    <Block>
      <Group>
        <Visibility.Show as={Button} {...visibility}>Show</Visibility.Show>
        <Visibility.Hide as={Button} {...visibility}>Hide</Visibility.Hide>
        <Visibility.Toggle as={Button} {...visibility}>Toggle</Visibility.Toggle>
      </Group>
      <Visibility {...visibility} hiddenStyle={{opacity: 0}} visibleStyle={{ opacity: 1}} transition="opacity 200ms">
        Visibility
      </Visibility>
    </Block>
  )}
</Visibility.Container>
```

**Comment by diegohaz** [comment]
The idea behind the name `Hidden` is that it's easier to infer that this won't be shown:
```jsx
<Hidden>Hi</Hidden>
```
It's "hidden by default". 

The HTML equivalent would be this:
```jsx
<div hidden>Hi</div>
```

`Visibility`, besides being very hard to type (😅), isn't explicit about its initial state. But I agree that `<Hidden visible>` may seem illogical at first. If it communicates well, though, I'm ok with it.

**Comment by diegohaz** [comment]
The current state (I'm really happy with this):

![jul-15-2018 15-54-55](https://user-images.githubusercontent.com/3068563/42737256-71df86fa-8847-11e8-90ee-dd7e73fc9384.gif)
